# Generated by Django 5.1.4 on 2024-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=100.0),
        ),
    ]
